### ISSUE TITLE
Tests for creating a new wp site with Ansible

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-si/wp-ops#257]
On migration-wp.epfl.ch (test) :

  - [x] Create a site from scratch, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-2018}  
         ✓ the default language is fr
  - [x] Re-run the same command, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-2018}  
         ✗ → Yellow for refresh menu, see #259 
  - [x] Re-run the same command, changing from lang={fr, de} to lang={it, en} in wp-veritas
         ✓ the default language is fr, no changes
  - [x] Create a site from scratch, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-light}  
         ✓ the theme "wp-theme-light" is installed and active
  - [x] Re-run the same command, changing theme={wp-theme-light} to theme={wp-theme-2018}  
         ✓ the theme "wp-theme-2018" is installed and active
         → is that what we want ?
  - [x] Create a site from scratch, lang={fr, de}, category={Inside}, theme={wp-theme-2018}  
         ✓ category's plugin `epfl-intranet` is installed and configured
  - [x] Re-run the same command, changing category={Inside} to category={GeneralPublic}
        ✓ category's plugin `epfl-intranet` is removed

Same tests on www.epfl.ch (prod) :
  - [x] Run the ansible command on a existing site canari2 
         ✓ Some changes are applied
  - [x] Re-run the ansible command on a existing site canari2
         ✓ all is green
  - [x] Delete a existing site 
         ✓ the site is completely deleted
  - [x] Create a site from scratch, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-2018}  
         ✓ the default language is fr
  - [x] Re-run the same command, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-2018}  
         ✓ the default language is fr, no changes
  - [x] Re-run the same command, changing from lang={fr, de} to lang={it, en} in wp-veritas
         ✓the default language is fr, no changes
  - [x] Create a site from scratch, lang={fr, de}, category={GeneralPublic}, theme={wp-theme-light}  
         ✓the theme "wp-theme-light" is installed and active
  - [x]  Re-run the same command, changing theme={wp-theme-light} to theme={wp-theme-2018}  
         ✓the theme "wp-theme-2018" is installed and active
  - [x] canari2 Create a site from scratch, lang={fr, de}, category={Inside}, theme={wp-theme-2018}  
         ✓category's plugins are installed and activated
  - [x] Re-run the same command, changing category={Inside} to category={GeneralPublic}
         ✓category's plugins are installed and activated

**Comment by ponsfrilus** [comment]
Tested with @epfl-si/wwp today.
