### ISSUE TITLE
Mise d'équerre des plugins: Le mode dry-run --check ne fonctionne pas

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-si/wp-ops#278]
Exemple de commande : 
```./wpsible --prod -e '{ "wp_destructive": { "www__labs__fimap" : ["config", "code"] }}' -t plugins -l www__labs__fimap --check```

![image](https://user-images.githubusercontent.com/4997224/85692775-f69d1380-b6d5-11ea-896d-ce8403dd5376.png)

**Comment by jdelasoie** [comment]
La solution devrait être d'ajouter `check_mode: no` sur les tâches qui sont des "inline facts" (des tâches qui sont utilises que pour setter une variable, comme _active_plugins
